server:
  port: 8079
logging:
  level: info
  file: ./agriculture.log

spring:
  datasource:
    url: jdbc:sqlserver://192.168.200.3:1433;database=jiaoxue
    username: sa
    password: Zte123

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  auto-dialect: sqlserver
  reasonable: true