server:
  port: 8079
logging:
  level: debug

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
